/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author depepe
 */
package chipper;

import javax.swing.JOptionPane;


public class Chipper {

    public static void main(String[] args) {
    tobiner Convert=new tobiner();
    String abjad,ab1,ab2,ab3,ab4,ab5,ab6,ab7,ab8;
    abjad=JOptionPane.showInputDialog("                 TUGAS MATA KULIAH\nPENGAMANAN KOMPUTER dan JARINGAN\n                 "
            + " -----[Chiper Text]-----\n\nMasukkan kata : ","Maksimal 8 karakter");
    int hitung=abjad.length();
if(hitung==1){
    ab1=abjad.substring(0,1);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
}
//===============================================================================================================
else if(hitung==2){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
    
}
//=====================================================================================================================
else if(hitung==3){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
    
}
//=================================================================================================
else if(hitung==4){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    ab4=abjad.substring(3,4);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
switch(ab4){
        case "A":Convert.abx=1;Convert.Hasil4();break;
        case "B":Convert.abx=2;Convert.Hasil4();break;
        case "C":Convert.abx=3;Convert.Hasil4();break;
        case "D":Convert.abx=4;Convert.Hasil4();break;
        case "E":Convert.abx=5;Convert.Hasil4();break;
        case "F":Convert.abx=6;Convert.Hasil4();break;
        case "G":Convert.abx=7;Convert.Hasil4();break;
        case "H":Convert.abx=8;Convert.Hasil4();break;
        case "I":Convert.abx=9;Convert.Hasil4();break;
        case "J":Convert.abx=10;Convert.Hasil4();break;
        case "K":Convert.abx=11;Convert.Hasil4();break;
        case "L":Convert.abx=12;Convert.Hasil4();break;
        case "M":Convert.abx=13;Convert.Hasil4();break;
        case "N":Convert.abx=14;Convert.Hasil4();break;
        case "O":Convert.abx=15;Convert.Hasil4();break;
        case "P":Convert.abx=16;Convert.Hasil4();break;
        case "Q":Convert.abx=17;Convert.Hasil4();break;
        case "R":Convert.abx=18;Convert.Hasil4();break;
        case "S":Convert.abx=19;Convert.Hasil4();break;
        case "T":Convert.abx=20;Convert.Hasil4();break;
        case "U":Convert.abx=21;Convert.Hasil4();break;
        case "V":Convert.abx=22;Convert.Hasil4();break;
        case "W":Convert.abx=23;Convert.Hasil4();break;
        case "X":Convert.abx=24;Convert.Hasil4();break;
        case "Y":Convert.abx=25;Convert.Hasil4();break;
        case "Z":Convert.abx=26;Convert.Hasil4();break;
        case "0":Convert.abx=27;Convert.Hasil4();break;
        case "1":Convert.abx=28;Convert.Hasil4();break;
        case "2":Convert.abx=29;Convert.Hasil4();break;
        case "3":Convert.abx=30;Convert.Hasil4();break;
        case "4":Convert.abx=31;Convert.Hasil4();break;
        case "5":Convert.abx=32;Convert.Hasil4();break;
        case "6":Convert.abx=33;Convert.Hasil4();break;
        case "7":Convert.abx=34;Convert.Hasil4();break;
        case "8":Convert.abx=35;Convert.Hasil4();break;
        case "9":Convert.abx=36;Convert.Hasil4();break;
    }
}
//=================================================================================================
else if(hitung==5){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    ab4=abjad.substring(3,4);
    ab5=abjad.substring(4,5);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
switch(ab4){
        case "A":Convert.abx=1;Convert.Hasil4();break;
        case "B":Convert.abx=2;Convert.Hasil4();break;
        case "C":Convert.abx=3;Convert.Hasil4();break;
        case "D":Convert.abx=4;Convert.Hasil4();break;
        case "E":Convert.abx=5;Convert.Hasil4();break;
        case "F":Convert.abx=6;Convert.Hasil4();break;
        case "G":Convert.abx=7;Convert.Hasil4();break;
        case "H":Convert.abx=8;Convert.Hasil4();break;
        case "I":Convert.abx=9;Convert.Hasil4();break;
        case "J":Convert.abx=10;Convert.Hasil4();break;
        case "K":Convert.abx=11;Convert.Hasil4();break;
        case "L":Convert.abx=12;Convert.Hasil4();break;
        case "M":Convert.abx=13;Convert.Hasil4();break;
        case "N":Convert.abx=14;Convert.Hasil4();break;
        case "O":Convert.abx=15;Convert.Hasil4();break;
        case "P":Convert.abx=16;Convert.Hasil4();break;
        case "Q":Convert.abx=17;Convert.Hasil4();break;
        case "R":Convert.abx=18;Convert.Hasil4();break;
        case "S":Convert.abx=19;Convert.Hasil4();break;
        case "T":Convert.abx=20;Convert.Hasil4();break;
        case "U":Convert.abx=21;Convert.Hasil4();break;
        case "V":Convert.abx=22;Convert.Hasil4();break;
        case "W":Convert.abx=23;Convert.Hasil4();break;
        case "X":Convert.abx=24;Convert.Hasil4();break;
        case "Y":Convert.abx=25;Convert.Hasil4();break;
        case "Z":Convert.abx=26;Convert.Hasil4();break;
        case "0":Convert.abx=27;Convert.Hasil4();break;
        case "1":Convert.abx=28;Convert.Hasil4();break;
        case "2":Convert.abx=29;Convert.Hasil4();break;
        case "3":Convert.abx=30;Convert.Hasil4();break;
        case "4":Convert.abx=31;Convert.Hasil4();break;
        case "5":Convert.abx=32;Convert.Hasil4();break;
        case "6":Convert.abx=33;Convert.Hasil4();break;
        case "7":Convert.abx=34;Convert.Hasil4();break;
        case "8":Convert.abx=35;Convert.Hasil4();break;
        case "9":Convert.abx=36;Convert.Hasil4();break;
    }
switch(ab5){
        case "A":Convert.abx=1;Convert.Hasil5();break;
        case "B":Convert.abx=2;Convert.Hasil5();break;
        case "C":Convert.abx=3;Convert.Hasil5();break;
        case "D":Convert.abx=4;Convert.Hasil5();break;
        case "E":Convert.abx=5;Convert.Hasil5();break;
        case "F":Convert.abx=6;Convert.Hasil5();break;
        case "G":Convert.abx=7;Convert.Hasil5();break;
        case "H":Convert.abx=8;Convert.Hasil5();break;
        case "I":Convert.abx=9;Convert.Hasil5();break;
        case "J":Convert.abx=10;Convert.Hasil5();break;
        case "K":Convert.abx=11;Convert.Hasil5();break;
        case "L":Convert.abx=12;Convert.Hasil5();break;
        case "M":Convert.abx=13;Convert.Hasil5();break;
        case "N":Convert.abx=14;Convert.Hasil5();break;
        case "O":Convert.abx=15;Convert.Hasil5();break;
        case "P":Convert.abx=16;Convert.Hasil5();break;
        case "Q":Convert.abx=17;Convert.Hasil5();break;
        case "R":Convert.abx=18;Convert.Hasil5();break;
        case "S":Convert.abx=19;Convert.Hasil5();break;
        case "T":Convert.abx=20;Convert.Hasil5();break;
        case "U":Convert.abx=21;Convert.Hasil5();break;
        case "V":Convert.abx=22;Convert.Hasil5();break;
        case "W":Convert.abx=23;Convert.Hasil5();break;
        case "X":Convert.abx=24;Convert.Hasil5();break;
        case "Y":Convert.abx=25;Convert.Hasil5();break;
        case "Z":Convert.abx=26;Convert.Hasil5();break;
        case "0":Convert.abx=27;Convert.Hasil5();break;
        case "1":Convert.abx=28;Convert.Hasil5();break;
        case "2":Convert.abx=29;Convert.Hasil5();break;
        case "3":Convert.abx=30;Convert.Hasil5();break;
        case "4":Convert.abx=31;Convert.Hasil5();break;
        case "5":Convert.abx=32;Convert.Hasil5();break;
        case "6":Convert.abx=33;Convert.Hasil5();break;
        case "7":Convert.abx=34;Convert.Hasil5();break;
        case "8":Convert.abx=35;Convert.Hasil5();break;
        case "9":Convert.abx=36;Convert.Hasil5();break;
    }
}
//=================================================================================================
else if(hitung==6){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    ab4=abjad.substring(3,4);
    ab5=abjad.substring(4,5);
    ab6=abjad.substring(5,6);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
switch(ab4){
        case "A":Convert.abx=1;Convert.Hasil4();break;
        case "B":Convert.abx=2;Convert.Hasil4();break;
        case "C":Convert.abx=3;Convert.Hasil4();break;
        case "D":Convert.abx=4;Convert.Hasil4();break;
        case "E":Convert.abx=5;Convert.Hasil4();break;
        case "F":Convert.abx=6;Convert.Hasil4();break;
        case "G":Convert.abx=7;Convert.Hasil4();break;
        case "H":Convert.abx=8;Convert.Hasil4();break;
        case "I":Convert.abx=9;Convert.Hasil4();break;
        case "J":Convert.abx=10;Convert.Hasil4();break;
        case "K":Convert.abx=11;Convert.Hasil4();break;
        case "L":Convert.abx=12;Convert.Hasil4();break;
        case "M":Convert.abx=13;Convert.Hasil4();break;
        case "N":Convert.abx=14;Convert.Hasil4();break;
        case "O":Convert.abx=15;Convert.Hasil4();break;
        case "P":Convert.abx=16;Convert.Hasil4();break;
        case "Q":Convert.abx=17;Convert.Hasil4();break;
        case "R":Convert.abx=18;Convert.Hasil4();break;
        case "S":Convert.abx=19;Convert.Hasil4();break;
        case "T":Convert.abx=20;Convert.Hasil4();break;
        case "U":Convert.abx=21;Convert.Hasil4();break;
        case "V":Convert.abx=22;Convert.Hasil4();break;
        case "W":Convert.abx=23;Convert.Hasil4();break;
        case "X":Convert.abx=24;Convert.Hasil4();break;
        case "Y":Convert.abx=25;Convert.Hasil4();break;
        case "Z":Convert.abx=26;Convert.Hasil4();break;
        case "0":Convert.abx=27;Convert.Hasil4();break;
        case "1":Convert.abx=28;Convert.Hasil4();break;
        case "2":Convert.abx=29;Convert.Hasil4();break;
        case "3":Convert.abx=30;Convert.Hasil4();break;
        case "4":Convert.abx=31;Convert.Hasil4();break;
        case "5":Convert.abx=32;Convert.Hasil4();break;
        case "6":Convert.abx=33;Convert.Hasil4();break;
        case "7":Convert.abx=34;Convert.Hasil4();break;
        case "8":Convert.abx=35;Convert.Hasil4();break;
        case "9":Convert.abx=36;Convert.Hasil4();break;
    }
switch(ab5){
        case "A":Convert.abx=1;Convert.Hasil5();break;
        case "B":Convert.abx=2;Convert.Hasil5();break;
        case "C":Convert.abx=3;Convert.Hasil5();break;
        case "D":Convert.abx=4;Convert.Hasil5();break;
        case "E":Convert.abx=5;Convert.Hasil5();break;
        case "F":Convert.abx=6;Convert.Hasil5();break;
        case "G":Convert.abx=7;Convert.Hasil5();break;
        case "H":Convert.abx=8;Convert.Hasil5();break;
        case "I":Convert.abx=9;Convert.Hasil5();break;
        case "J":Convert.abx=10;Convert.Hasil5();break;
        case "K":Convert.abx=11;Convert.Hasil5();break;
        case "L":Convert.abx=12;Convert.Hasil5();break;
        case "M":Convert.abx=13;Convert.Hasil5();break;
        case "N":Convert.abx=14;Convert.Hasil5();break;
        case "O":Convert.abx=15;Convert.Hasil5();break;
        case "P":Convert.abx=16;Convert.Hasil5();break;
        case "Q":Convert.abx=17;Convert.Hasil5();break;
        case "R":Convert.abx=18;Convert.Hasil5();break;
        case "S":Convert.abx=19;Convert.Hasil5();break;
        case "T":Convert.abx=20;Convert.Hasil5();break;
        case "U":Convert.abx=21;Convert.Hasil5();break;
        case "V":Convert.abx=22;Convert.Hasil5();break;
        case "W":Convert.abx=23;Convert.Hasil5();break;
        case "X":Convert.abx=24;Convert.Hasil5();break;
        case "Y":Convert.abx=25;Convert.Hasil5();break;
        case "Z":Convert.abx=26;Convert.Hasil5();break;
        case "0":Convert.abx=27;Convert.Hasil5();break;
        case "1":Convert.abx=28;Convert.Hasil5();break;
        case "2":Convert.abx=29;Convert.Hasil5();break;
        case "3":Convert.abx=30;Convert.Hasil5();break;
        case "4":Convert.abx=31;Convert.Hasil5();break;
        case "5":Convert.abx=32;Convert.Hasil5();break;
        case "6":Convert.abx=33;Convert.Hasil5();break;
        case "7":Convert.abx=34;Convert.Hasil5();break;
        case "8":Convert.abx=35;Convert.Hasil5();break;
        case "9":Convert.abx=36;Convert.Hasil5();break;
}
switch(ab6){
        case "A":Convert.abx=1;Convert.Hasil6();break;
        case "B":Convert.abx=2;Convert.Hasil6();break;
        case "C":Convert.abx=3;Convert.Hasil6();break;
        case "D":Convert.abx=4;Convert.Hasil6();break;
        case "E":Convert.abx=5;Convert.Hasil6();break;
        case "F":Convert.abx=6;Convert.Hasil6();break;
        case "G":Convert.abx=7;Convert.Hasil6();break;
        case "H":Convert.abx=8;Convert.Hasil6();break;
        case "I":Convert.abx=9;Convert.Hasil6();break;
        case "J":Convert.abx=10;Convert.Hasil6();break;
        case "K":Convert.abx=11;Convert.Hasil6();break;
        case "L":Convert.abx=12;Convert.Hasil6();break;
        case "M":Convert.abx=13;Convert.Hasil6();break;
        case "N":Convert.abx=14;Convert.Hasil6();break;
        case "O":Convert.abx=15;Convert.Hasil6();break;
        case "P":Convert.abx=16;Convert.Hasil6();break;
        case "Q":Convert.abx=17;Convert.Hasil6();break;
        case "R":Convert.abx=18;Convert.Hasil6();break;
        case "S":Convert.abx=19;Convert.Hasil6();break;
        case "T":Convert.abx=20;Convert.Hasil6();break;
        case "U":Convert.abx=21;Convert.Hasil6();break;
        case "V":Convert.abx=22;Convert.Hasil6();break;
        case "W":Convert.abx=23;Convert.Hasil6();break;
        case "X":Convert.abx=24;Convert.Hasil6();break;
        case "Y":Convert.abx=25;Convert.Hasil6();break;
        case "Z":Convert.abx=26;Convert.Hasil6();break;
        case "0":Convert.abx=27;Convert.Hasil6();break;
        case "1":Convert.abx=28;Convert.Hasil6();break;
        case "2":Convert.abx=29;Convert.Hasil6();break;
        case "3":Convert.abx=30;Convert.Hasil6();break;
        case "4":Convert.abx=31;Convert.Hasil6();break;
        case "5":Convert.abx=32;Convert.Hasil6();break;
        case "6":Convert.abx=33;Convert.Hasil6();break;
        case "7":Convert.abx=34;Convert.Hasil6();break;
        case "8":Convert.abx=35;Convert.Hasil6();break;
        case "9":Convert.abx=36;Convert.Hasil6();break;
    }
}
//=================================================================================================
else if(hitung==7){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    ab4=abjad.substring(3,4);
    ab5=abjad.substring(4,5);
    ab6=abjad.substring(5,6);
    ab7=abjad.substring(6,7);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
switch(ab4){
        case "A":Convert.abx=1;Convert.Hasil4();break;
        case "B":Convert.abx=2;Convert.Hasil4();break;
        case "C":Convert.abx=3;Convert.Hasil4();break;
        case "D":Convert.abx=4;Convert.Hasil4();break;
        case "E":Convert.abx=5;Convert.Hasil4();break;
        case "F":Convert.abx=6;Convert.Hasil4();break;
        case "G":Convert.abx=7;Convert.Hasil4();break;
        case "H":Convert.abx=8;Convert.Hasil4();break;
        case "I":Convert.abx=9;Convert.Hasil4();break;
        case "J":Convert.abx=10;Convert.Hasil4();break;
        case "K":Convert.abx=11;Convert.Hasil4();break;
        case "L":Convert.abx=12;Convert.Hasil4();break;
        case "M":Convert.abx=13;Convert.Hasil4();break;
        case "N":Convert.abx=14;Convert.Hasil4();break;
        case "O":Convert.abx=15;Convert.Hasil4();break;
        case "P":Convert.abx=16;Convert.Hasil4();break;
        case "Q":Convert.abx=17;Convert.Hasil4();break;
        case "R":Convert.abx=18;Convert.Hasil4();break;
        case "S":Convert.abx=19;Convert.Hasil4();break;
        case "T":Convert.abx=20;Convert.Hasil4();break;
        case "U":Convert.abx=21;Convert.Hasil4();break;
        case "V":Convert.abx=22;Convert.Hasil4();break;
        case "W":Convert.abx=23;Convert.Hasil4();break;
        case "X":Convert.abx=24;Convert.Hasil4();break;
        case "Y":Convert.abx=25;Convert.Hasil4();break;
        case "Z":Convert.abx=26;Convert.Hasil4();break;
        case "0":Convert.abx=27;Convert.Hasil4();break;
        case "1":Convert.abx=28;Convert.Hasil4();break;
        case "2":Convert.abx=29;Convert.Hasil4();break;
        case "3":Convert.abx=30;Convert.Hasil4();break;
        case "4":Convert.abx=31;Convert.Hasil4();break;
        case "5":Convert.abx=32;Convert.Hasil4();break;
        case "6":Convert.abx=33;Convert.Hasil4();break;
        case "7":Convert.abx=34;Convert.Hasil4();break;
        case "8":Convert.abx=35;Convert.Hasil4();break;
        case "9":Convert.abx=36;Convert.Hasil4();break;
    }
switch(ab5){
        case "A":Convert.abx=1;Convert.Hasil5();break;
        case "B":Convert.abx=2;Convert.Hasil5();break;
        case "C":Convert.abx=3;Convert.Hasil5();break;
        case "D":Convert.abx=4;Convert.Hasil5();break;
        case "E":Convert.abx=5;Convert.Hasil5();break;
        case "F":Convert.abx=6;Convert.Hasil5();break;
        case "G":Convert.abx=7;Convert.Hasil5();break;
        case "H":Convert.abx=8;Convert.Hasil5();break;
        case "I":Convert.abx=9;Convert.Hasil5();break;
        case "J":Convert.abx=10;Convert.Hasil5();break;
        case "K":Convert.abx=11;Convert.Hasil5();break;
        case "L":Convert.abx=12;Convert.Hasil5();break;
        case "M":Convert.abx=13;Convert.Hasil5();break;
        case "N":Convert.abx=14;Convert.Hasil5();break;
        case "O":Convert.abx=15;Convert.Hasil5();break;
        case "P":Convert.abx=16;Convert.Hasil5();break;
        case "Q":Convert.abx=17;Convert.Hasil5();break;
        case "R":Convert.abx=18;Convert.Hasil5();break;
        case "S":Convert.abx=19;Convert.Hasil5();break;
        case "T":Convert.abx=20;Convert.Hasil5();break;
        case "U":Convert.abx=21;Convert.Hasil5();break;
        case "V":Convert.abx=22;Convert.Hasil5();break;
        case "W":Convert.abx=23;Convert.Hasil5();break;
        case "X":Convert.abx=24;Convert.Hasil5();break;
        case "Y":Convert.abx=25;Convert.Hasil5();break;
        case "Z":Convert.abx=26;Convert.Hasil5();break;
        case "0":Convert.abx=27;Convert.Hasil5();break;
        case "1":Convert.abx=28;Convert.Hasil5();break;
        case "2":Convert.abx=29;Convert.Hasil5();break;
        case "3":Convert.abx=30;Convert.Hasil5();break;
        case "4":Convert.abx=31;Convert.Hasil5();break;
        case "5":Convert.abx=32;Convert.Hasil5();break;
        case "6":Convert.abx=33;Convert.Hasil5();break;
        case "7":Convert.abx=34;Convert.Hasil5();break;
        case "8":Convert.abx=35;Convert.Hasil5();break;
        case "9":Convert.abx=36;Convert.Hasil5();break;
}
switch(ab6){
        case "A":Convert.abx=1;Convert.Hasil6();break;
        case "B":Convert.abx=2;Convert.Hasil6();break;
        case "C":Convert.abx=3;Convert.Hasil6();break;
        case "D":Convert.abx=4;Convert.Hasil6();break;
        case "E":Convert.abx=5;Convert.Hasil6();break;
        case "F":Convert.abx=6;Convert.Hasil6();break;
        case "G":Convert.abx=7;Convert.Hasil6();break;
        case "H":Convert.abx=8;Convert.Hasil6();break;
        case "I":Convert.abx=9;Convert.Hasil6();break;
        case "J":Convert.abx=10;Convert.Hasil6();break;
        case "K":Convert.abx=11;Convert.Hasil6();break;
        case "L":Convert.abx=12;Convert.Hasil6();break;
        case "M":Convert.abx=13;Convert.Hasil6();break;
        case "N":Convert.abx=14;Convert.Hasil6();break;
        case "O":Convert.abx=15;Convert.Hasil6();break;
        case "P":Convert.abx=16;Convert.Hasil6();break;
        case "Q":Convert.abx=17;Convert.Hasil6();break;
        case "R":Convert.abx=18;Convert.Hasil6();break;
        case "S":Convert.abx=19;Convert.Hasil6();break;
        case "T":Convert.abx=20;Convert.Hasil6();break;
        case "U":Convert.abx=21;Convert.Hasil6();break;
        case "V":Convert.abx=22;Convert.Hasil6();break;
        case "W":Convert.abx=23;Convert.Hasil6();break;
        case "X":Convert.abx=24;Convert.Hasil6();break;
        case "Y":Convert.abx=25;Convert.Hasil6();break;
        case "Z":Convert.abx=26;Convert.Hasil6();break;
        case "0":Convert.abx=27;Convert.Hasil6();break;
        case "1":Convert.abx=28;Convert.Hasil6();break;
        case "2":Convert.abx=29;Convert.Hasil6();break;
        case "3":Convert.abx=30;Convert.Hasil6();break;
        case "4":Convert.abx=31;Convert.Hasil6();break;
        case "5":Convert.abx=32;Convert.Hasil6();break;
        case "6":Convert.abx=33;Convert.Hasil6();break;
        case "7":Convert.abx=34;Convert.Hasil6();break;
        case "8":Convert.abx=35;Convert.Hasil6();break;
        case "9":Convert.abx=36;Convert.Hasil6();break;
    }
switch(ab7){
        case "A":Convert.abx=1;Convert.Hasil7();break;
        case "B":Convert.abx=2;Convert.Hasil7();break;
        case "C":Convert.abx=3;Convert.Hasil7();break;
        case "D":Convert.abx=4;Convert.Hasil7();break;
        case "E":Convert.abx=5;Convert.Hasil7();break;
        case "F":Convert.abx=6;Convert.Hasil7();break;
        case "G":Convert.abx=7;Convert.Hasil7();break;
        case "H":Convert.abx=8;Convert.Hasil7();break;
        case "I":Convert.abx=9;Convert.Hasil7();break;
        case "J":Convert.abx=10;Convert.Hasil7();break;
        case "K":Convert.abx=11;Convert.Hasil7();break;
        case "L":Convert.abx=12;Convert.Hasil7();break;
        case "M":Convert.abx=13;Convert.Hasil7();break;
        case "N":Convert.abx=14;Convert.Hasil7();break;
        case "O":Convert.abx=15;Convert.Hasil7();break;
        case "P":Convert.abx=16;Convert.Hasil7();break;
        case "Q":Convert.abx=17;Convert.Hasil7();break;
        case "R":Convert.abx=18;Convert.Hasil7();break;
        case "S":Convert.abx=19;Convert.Hasil7();break;
        case "T":Convert.abx=20;Convert.Hasil7();break;
        case "U":Convert.abx=21;Convert.Hasil7();break;
        case "V":Convert.abx=22;Convert.Hasil7();break;
        case "W":Convert.abx=23;Convert.Hasil7();break;
        case "X":Convert.abx=24;Convert.Hasil7();break;
        case "Y":Convert.abx=25;Convert.Hasil7();break;
        case "Z":Convert.abx=26;Convert.Hasil7();break;
        case "0":Convert.abx=27;Convert.Hasil7();break;
        case "1":Convert.abx=28;Convert.Hasil7();break;
        case "2":Convert.abx=29;Convert.Hasil7();break;
        case "3":Convert.abx=30;Convert.Hasil7();break;
        case "4":Convert.abx=31;Convert.Hasil7();break;
        case "5":Convert.abx=32;Convert.Hasil7();break;
        case "6":Convert.abx=33;Convert.Hasil7();break;
        case "7":Convert.abx=34;Convert.Hasil7();break;
        case "8":Convert.abx=35;Convert.Hasil7();break;
        case "9":Convert.abx=36;Convert.Hasil7();break;
    }
}
//=================================================================================================
else if(hitung==8){
    ab1=abjad.substring(0,1);
    ab2=abjad.substring(1,2);
    ab3=abjad.substring(2,3);
    ab4=abjad.substring(3,4);
    ab5=abjad.substring(4,5);
    ab6=abjad.substring(5,6);
    ab7=abjad.substring(6,7);
    ab8=abjad.substring(7,8);
    switch(ab1){
        case "A":Convert.abx=1;Convert.Hasil1();break;
        case "B":Convert.abx=2;Convert.Hasil1();break;
        case "C":Convert.abx=3;Convert.Hasil1();break;
        case "D":Convert.abx=4;Convert.Hasil1();break;
        case "E":Convert.abx=5;Convert.Hasil1();break;
        case "F":Convert.abx=6;Convert.Hasil1();break;
        case "G":Convert.abx=7;Convert.Hasil1();break;
        case "H":Convert.abx=8;Convert.Hasil1();break;
        case "I":Convert.abx=9;Convert.Hasil1();break;
        case "J":Convert.abx=10;Convert.Hasil1();break;
        case "K":Convert.abx=11;Convert.Hasil1();break;
        case "L":Convert.abx=12;Convert.Hasil1();break;
        case "M":Convert.abx=13;Convert.Hasil1();break;
        case "N":Convert.abx=14;Convert.Hasil1();break;
        case "O":Convert.abx=15;Convert.Hasil1();break;
        case "P":Convert.abx=16;Convert.Hasil1();break;
        case "Q":Convert.abx=17;Convert.Hasil1();break;
        case "R":Convert.abx=18;Convert.Hasil1();break;
        case "S":Convert.abx=19;Convert.Hasil1();break;
        case "T":Convert.abx=20;Convert.Hasil1();break;
        case "U":Convert.abx=21;Convert.Hasil1();break;
        case "V":Convert.abx=22;Convert.Hasil1();break;
        case "W":Convert.abx=23;Convert.Hasil1();break;
        case "X":Convert.abx=24;Convert.Hasil1();break;
        case "Y":Convert.abx=25;Convert.Hasil1();break;
        case "Z":Convert.abx=26;Convert.Hasil1();break;
        case "0":Convert.abx=27;Convert.Hasil1();break;
        case "1":Convert.abx=28;Convert.Hasil1();break;
        case "2":Convert.abx=29;Convert.Hasil1();break;
        case "3":Convert.abx=30;Convert.Hasil1();break;
        case "4":Convert.abx=31;Convert.Hasil1();break;
        case "5":Convert.abx=32;Convert.Hasil1();break;
        case "6":Convert.abx=33;Convert.Hasil1();break;
        case "7":Convert.abx=34;Convert.Hasil1();break;
        case "8":Convert.abx=35;Convert.Hasil1();break;
        case "9":Convert.abx=36;Convert.Hasil1();break;
    }
switch(ab2){
        case "A":Convert.abx=1;Convert.Hasil2();break;
        case "B":Convert.abx=2;Convert.Hasil2();break;
        case "C":Convert.abx=3;Convert.Hasil2();break;
        case "D":Convert.abx=4;Convert.Hasil2();break;
        case "E":Convert.abx=5;Convert.Hasil2();break;
        case "F":Convert.abx=6;Convert.Hasil2();break;
        case "G":Convert.abx=7;Convert.Hasil2();break;
        case "H":Convert.abx=8;Convert.Hasil2();break;
        case "I":Convert.abx=9;Convert.Hasil2();break;
        case "J":Convert.abx=10;Convert.Hasil2();break;
        case "K":Convert.abx=11;Convert.Hasil2();break;
        case "L":Convert.abx=12;Convert.Hasil2();break;
        case "M":Convert.abx=13;Convert.Hasil2();break;
        case "N":Convert.abx=14;Convert.Hasil2();break;
        case "O":Convert.abx=15;Convert.Hasil2();break;
        case "P":Convert.abx=16;Convert.Hasil2();break;
        case "Q":Convert.abx=17;Convert.Hasil2();break;
        case "R":Convert.abx=18;Convert.Hasil2();break;
        case "S":Convert.abx=19;Convert.Hasil2();break;
        case "T":Convert.abx=20;Convert.Hasil2();break;
        case "U":Convert.abx=21;Convert.Hasil2();break;
        case "V":Convert.abx=22;Convert.Hasil2();break;
        case "W":Convert.abx=23;Convert.Hasil2();break;
        case "X":Convert.abx=24;Convert.Hasil2();break;
        case "Y":Convert.abx=25;Convert.Hasil2();break;
        case "Z":Convert.abx=26;Convert.Hasil2();break;
        case "0":Convert.abx=27;Convert.Hasil2();break;
        case "1":Convert.abx=28;Convert.Hasil2();break;
        case "2":Convert.abx=29;Convert.Hasil2();break;
        case "3":Convert.abx=30;Convert.Hasil2();break;
        case "4":Convert.abx=31;Convert.Hasil2();break;
        case "5":Convert.abx=32;Convert.Hasil2();break;
        case "6":Convert.abx=33;Convert.Hasil2();break;
        case "7":Convert.abx=34;Convert.Hasil2();break;
        case "8":Convert.abx=35;Convert.Hasil2();break;
        case "9":Convert.abx=36;Convert.Hasil2();break;
    }
switch(ab3){
        case "A":Convert.abx=1;Convert.Hasil3();break;
        case "B":Convert.abx=2;Convert.Hasil3();break;
        case "C":Convert.abx=3;Convert.Hasil3();break;
        case "D":Convert.abx=4;Convert.Hasil3();break;
        case "E":Convert.abx=5;Convert.Hasil3();break;
        case "F":Convert.abx=6;Convert.Hasil3();break;
        case "G":Convert.abx=7;Convert.Hasil3();break;
        case "H":Convert.abx=8;Convert.Hasil3();break;
        case "I":Convert.abx=9;Convert.Hasil3();break;
        case "J":Convert.abx=10;Convert.Hasil3();break;
        case "K":Convert.abx=11;Convert.Hasil3();break;
        case "L":Convert.abx=12;Convert.Hasil3();break;
        case "M":Convert.abx=13;Convert.Hasil3();break;
        case "N":Convert.abx=14;Convert.Hasil3();break;
        case "O":Convert.abx=15;Convert.Hasil3();break;
        case "P":Convert.abx=16;Convert.Hasil3();break;
        case "Q":Convert.abx=17;Convert.Hasil3();break;
        case "R":Convert.abx=18;Convert.Hasil3();break;
        case "S":Convert.abx=19;Convert.Hasil3();break;
        case "T":Convert.abx=20;Convert.Hasil3();break;
        case "U":Convert.abx=21;Convert.Hasil3();break;
        case "V":Convert.abx=22;Convert.Hasil3();break;
        case "W":Convert.abx=23;Convert.Hasil3();break;
        case "X":Convert.abx=24;Convert.Hasil3();break;
        case "Y":Convert.abx=25;Convert.Hasil3();break;
        case "Z":Convert.abx=26;Convert.Hasil3();break;
        case "0":Convert.abx=27;Convert.Hasil3();break;
        case "1":Convert.abx=28;Convert.Hasil3();break;
        case "2":Convert.abx=29;Convert.Hasil3();break;
        case "3":Convert.abx=30;Convert.Hasil3();break;
        case "4":Convert.abx=31;Convert.Hasil3();break;
        case "5":Convert.abx=32;Convert.Hasil3();break;
        case "6":Convert.abx=33;Convert.Hasil3();break;
        case "7":Convert.abx=34;Convert.Hasil3();break;
        case "8":Convert.abx=35;Convert.Hasil3();break;
        case "9":Convert.abx=36;Convert.Hasil3();break;
    }
switch(ab4){
        case "A":Convert.abx=1;Convert.Hasil4();break;
        case "B":Convert.abx=2;Convert.Hasil4();break;
        case "C":Convert.abx=3;Convert.Hasil4();break;
        case "D":Convert.abx=4;Convert.Hasil4();break;
        case "E":Convert.abx=5;Convert.Hasil4();break;
        case "F":Convert.abx=6;Convert.Hasil4();break;
        case "G":Convert.abx=7;Convert.Hasil4();break;
        case "H":Convert.abx=8;Convert.Hasil4();break;
        case "I":Convert.abx=9;Convert.Hasil4();break;
        case "J":Convert.abx=10;Convert.Hasil4();break;
        case "K":Convert.abx=11;Convert.Hasil4();break;
        case "L":Convert.abx=12;Convert.Hasil4();break;
        case "M":Convert.abx=13;Convert.Hasil4();break;
        case "N":Convert.abx=14;Convert.Hasil4();break;
        case "O":Convert.abx=15;Convert.Hasil4();break;
        case "P":Convert.abx=16;Convert.Hasil4();break;
        case "Q":Convert.abx=17;Convert.Hasil4();break;
        case "R":Convert.abx=18;Convert.Hasil4();break;
        case "S":Convert.abx=19;Convert.Hasil4();break;
        case "T":Convert.abx=20;Convert.Hasil4();break;
        case "U":Convert.abx=21;Convert.Hasil4();break;
        case "V":Convert.abx=22;Convert.Hasil4();break;
        case "W":Convert.abx=23;Convert.Hasil4();break;
        case "X":Convert.abx=24;Convert.Hasil4();break;
        case "Y":Convert.abx=25;Convert.Hasil4();break;
        case "Z":Convert.abx=26;Convert.Hasil4();break;
        case "0":Convert.abx=27;Convert.Hasil4();break;
        case "1":Convert.abx=28;Convert.Hasil4();break;
        case "2":Convert.abx=29;Convert.Hasil4();break;
        case "3":Convert.abx=30;Convert.Hasil4();break;
        case "4":Convert.abx=31;Convert.Hasil4();break;
        case "5":Convert.abx=32;Convert.Hasil4();break;
        case "6":Convert.abx=33;Convert.Hasil4();break;
        case "7":Convert.abx=34;Convert.Hasil4();break;
        case "8":Convert.abx=35;Convert.Hasil4();break;
        case "9":Convert.abx=36;Convert.Hasil4();break;
    }
switch(ab5){
        case "A":Convert.abx=1;Convert.Hasil5();break;
        case "B":Convert.abx=2;Convert.Hasil5();break;
        case "C":Convert.abx=3;Convert.Hasil5();break;
        case "D":Convert.abx=4;Convert.Hasil5();break;
        case "E":Convert.abx=5;Convert.Hasil5();break;
        case "F":Convert.abx=6;Convert.Hasil5();break;
        case "G":Convert.abx=7;Convert.Hasil5();break;
        case "H":Convert.abx=8;Convert.Hasil5();break;
        case "I":Convert.abx=9;Convert.Hasil5();break;
        case "J":Convert.abx=10;Convert.Hasil5();break;
        case "K":Convert.abx=11;Convert.Hasil5();break;
        case "L":Convert.abx=12;Convert.Hasil5();break;
        case "M":Convert.abx=13;Convert.Hasil5();break;
        case "N":Convert.abx=14;Convert.Hasil5();break;
        case "O":Convert.abx=15;Convert.Hasil5();break;
        case "P":Convert.abx=16;Convert.Hasil5();break;
        case "Q":Convert.abx=17;Convert.Hasil5();break;
        case "R":Convert.abx=18;Convert.Hasil5();break;
        case "S":Convert.abx=19;Convert.Hasil5();break;
        case "T":Convert.abx=20;Convert.Hasil5();break;
        case "U":Convert.abx=21;Convert.Hasil5();break;
        case "V":Convert.abx=22;Convert.Hasil5();break;
        case "W":Convert.abx=23;Convert.Hasil5();break;
        case "X":Convert.abx=24;Convert.Hasil5();break;
        case "Y":Convert.abx=25;Convert.Hasil5();break;
        case "Z":Convert.abx=26;Convert.Hasil5();break;
        case "0":Convert.abx=27;Convert.Hasil5();break;
        case "1":Convert.abx=28;Convert.Hasil5();break;
        case "2":Convert.abx=29;Convert.Hasil5();break;
        case "3":Convert.abx=30;Convert.Hasil5();break;
        case "4":Convert.abx=31;Convert.Hasil5();break;
        case "5":Convert.abx=32;Convert.Hasil5();break;
        case "6":Convert.abx=33;Convert.Hasil5();break;
        case "7":Convert.abx=34;Convert.Hasil5();break;
        case "8":Convert.abx=35;Convert.Hasil5();break;
        case "9":Convert.abx=36;Convert.Hasil5();break;
}
switch(ab6){
        case "A":Convert.abx=1;Convert.Hasil6();break;
        case "B":Convert.abx=2;Convert.Hasil6();break;
        case "C":Convert.abx=3;Convert.Hasil6();break;
        case "D":Convert.abx=4;Convert.Hasil6();break;
        case "E":Convert.abx=5;Convert.Hasil6();break;
        case "F":Convert.abx=6;Convert.Hasil6();break;
        case "G":Convert.abx=7;Convert.Hasil6();break;
        case "H":Convert.abx=8;Convert.Hasil6();break;
        case "I":Convert.abx=9;Convert.Hasil6();break;
        case "J":Convert.abx=10;Convert.Hasil6();break;
        case "K":Convert.abx=11;Convert.Hasil6();break;
        case "L":Convert.abx=12;Convert.Hasil6();break;
        case "M":Convert.abx=13;Convert.Hasil6();break;
        case "N":Convert.abx=14;Convert.Hasil6();break;
        case "O":Convert.abx=15;Convert.Hasil6();break;
        case "P":Convert.abx=16;Convert.Hasil6();break;
        case "Q":Convert.abx=17;Convert.Hasil6();break;
        case "R":Convert.abx=18;Convert.Hasil6();break;
        case "S":Convert.abx=19;Convert.Hasil6();break;
        case "T":Convert.abx=20;Convert.Hasil6();break;
        case "U":Convert.abx=21;Convert.Hasil6();break;
        case "V":Convert.abx=22;Convert.Hasil6();break;
        case "W":Convert.abx=23;Convert.Hasil6();break;
        case "X":Convert.abx=24;Convert.Hasil6();break;
        case "Y":Convert.abx=25;Convert.Hasil6();break;
        case "Z":Convert.abx=26;Convert.Hasil6();break;
        case "0":Convert.abx=27;Convert.Hasil6();break;
        case "1":Convert.abx=28;Convert.Hasil6();break;
        case "2":Convert.abx=29;Convert.Hasil6();break;
        case "3":Convert.abx=30;Convert.Hasil6();break;
        case "4":Convert.abx=31;Convert.Hasil6();break;
        case "5":Convert.abx=32;Convert.Hasil6();break;
        case "6":Convert.abx=33;Convert.Hasil6();break;
        case "7":Convert.abx=34;Convert.Hasil6();break;
        case "8":Convert.abx=35;Convert.Hasil6();break;
        case "9":Convert.abx=36;Convert.Hasil6();break;
    }
switch(ab7){
        case "A":Convert.abx=1;Convert.Hasil7();break;
        case "B":Convert.abx=2;Convert.Hasil7();break;
        case "C":Convert.abx=3;Convert.Hasil7();break;
        case "D":Convert.abx=4;Convert.Hasil7();break;
        case "E":Convert.abx=5;Convert.Hasil7();break;
        case "F":Convert.abx=6;Convert.Hasil7();break;
        case "G":Convert.abx=7;Convert.Hasil7();break;
        case "H":Convert.abx=8;Convert.Hasil7();break;
        case "I":Convert.abx=9;Convert.Hasil7();break;
        case "J":Convert.abx=10;Convert.Hasil7();break;
        case "K":Convert.abx=11;Convert.Hasil7();break;
        case "L":Convert.abx=12;Convert.Hasil7();break;
        case "M":Convert.abx=13;Convert.Hasil7();break;
        case "N":Convert.abx=14;Convert.Hasil7();break;
        case "O":Convert.abx=15;Convert.Hasil7();break;
        case "P":Convert.abx=16;Convert.Hasil7();break;
        case "Q":Convert.abx=17;Convert.Hasil7();break;
        case "R":Convert.abx=18;Convert.Hasil7();break;
        case "S":Convert.abx=19;Convert.Hasil7();break;
        case "T":Convert.abx=20;Convert.Hasil7();break;
        case "U":Convert.abx=21;Convert.Hasil7();break;
        case "V":Convert.abx=22;Convert.Hasil7();break;
        case "W":Convert.abx=23;Convert.Hasil7();break;
        case "X":Convert.abx=24;Convert.Hasil7();break;
        case "Y":Convert.abx=25;Convert.Hasil7();break;
        case "Z":Convert.abx=26;Convert.Hasil7();break;
        case "0":Convert.abx=27;Convert.Hasil7();break;
        case "1":Convert.abx=28;Convert.Hasil7();break;
        case "2":Convert.abx=29;Convert.Hasil7();break;
        case "3":Convert.abx=30;Convert.Hasil7();break;
        case "4":Convert.abx=31;Convert.Hasil7();break;
        case "5":Convert.abx=32;Convert.Hasil7();break;
        case "6":Convert.abx=33;Convert.Hasil7();break;
        case "7":Convert.abx=34;Convert.Hasil7();break;
        case "8":Convert.abx=35;Convert.Hasil7();break;
        case "9":Convert.abx=36;Convert.Hasil7();break;
    }
switch(ab8){
        case "A":Convert.abx=1;Convert.Hasil8();break;
        case "B":Convert.abx=2;Convert.Hasil8();break;
        case "C":Convert.abx=3;Convert.Hasil8();break;
        case "D":Convert.abx=4;Convert.Hasil8();break;
        case "E":Convert.abx=5;Convert.Hasil8();break;
        case "F":Convert.abx=6;Convert.Hasil8();break;
        case "G":Convert.abx=7;Convert.Hasil8();break;
        case "H":Convert.abx=8;Convert.Hasil8();break;
        case "I":Convert.abx=9;Convert.Hasil8();break;
        case "J":Convert.abx=10;Convert.Hasil8();break;
        case "K":Convert.abx=11;Convert.Hasil8();break;
        case "L":Convert.abx=12;Convert.Hasil8();break;
        case "M":Convert.abx=13;Convert.Hasil8();break;
        case "N":Convert.abx=14;Convert.Hasil8();break;
        case "O":Convert.abx=15;Convert.Hasil8();break;
        case "P":Convert.abx=16;Convert.Hasil8();break;
        case "Q":Convert.abx=17;Convert.Hasil8();break;
        case "R":Convert.abx=18;Convert.Hasil8();break;
        case "S":Convert.abx=19;Convert.Hasil8();break;
        case "T":Convert.abx=20;Convert.Hasil8();break;
        case "U":Convert.abx=21;Convert.Hasil8();break;
        case "V":Convert.abx=22;Convert.Hasil8();break;
        case "W":Convert.abx=23;Convert.Hasil8();break;
        case "X":Convert.abx=24;Convert.Hasil8();break;
        case "Y":Convert.abx=25;Convert.Hasil8();break;
        case "Z":Convert.abx=26;Convert.Hasil8();break;
        case "0":Convert.abx=27;Convert.Hasil8();break;
        case "1":Convert.abx=28;Convert.Hasil8();break;
        case "2":Convert.abx=29;Convert.Hasil8();break;
        case "3":Convert.abx=30;Convert.Hasil8();break;
        case "4":Convert.abx=31;Convert.Hasil8();break;
        case "5":Convert.abx=32;Convert.Hasil8();break;
        case "6":Convert.abx=33;Convert.Hasil8();break;
        case "7":Convert.abx=34;Convert.Hasil8();break;
        case "8":Convert.abx=35;Convert.Hasil8();break;
        case "9":Convert.abx=36;Convert.Hasil8();break;
    }
}

    if (abjad=="inputan salah"){
        JOptionPane.showMessageDialog(null," invalid input"," ",JOptionPane.ERROR_MESSAGE);
        }
    else if(hitung>=9){
        JOptionPane.showMessageDialog(null," Input melebihi batas maksimum"," ",JOptionPane.ERROR_MESSAGE);
    }
    else if(hitung==1){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==2){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==3){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==4){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin+" "+Convert.ab4bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==5){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin+" "+Convert.ab4bin+" "+Convert.ab5bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==6){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin+" "+Convert.ab4bin+" "+Convert.ab5bin+" "+Convert.ab6bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==7){
        
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin+" "+Convert.ab4bin+" "+Convert.ab5bin+" "+Convert.ab6bin+" "+Convert.ab7bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
    else if(hitung==8){
        JOptionPane.showMessageDialog(null,"---- Chiper Text by 12622070 ----\n\nKata Masukan  : "+abjad+"\nHasil Convert    :  "+Convert.ab1bin+" "+Convert.ab2bin+" "+Convert.ab3bin+" "+Convert.ab4bin+" "+Convert.ab5bin+" "+Convert.ab6bin+" "+Convert.ab7bin+" "+Convert.ab8bin,"Hasil",JOptionPane.INFORMATION_MESSAGE);
        }
   
    
}
}

